### ISSUE TITLE
Pretrained C3d Model

### ISSUE THREAD

**Issue by SateeshKumar21** [IkeaASM/IKEA_ASM_Dataset#1]
Hello,

I see that you use a C3d model pre-trained on Sports1M. Can you please share the link to that model. This repo does provide the aforementioned model: https://github.com/DavideA/c3d-pytorch. But, it will be great if you could confirm which one you used for your experiments.

Thank you.

**Comment by sitzikbs** [comment]
Yes, this is the exact one that was used. I'll update the readme to include this link.

**Comment by sitzikbs** [comment]
updated action readme with links to C3D and P3D. Hence closing.
