### ISSUE TITLE
Visualizing the pose data

### ISSUE THREAD

**Issue by vaithak** [IkeaASM/IKEA_ASM_Dataset#11]
Is there a way to visualize only the pose data without the need to download 240 GB of video data? 
I have downloaded the pose annotations as well as other utility files from Google drive, then I tried using the `IKEA_ASM_Dataset/action/visualization/pose_visualization.py` script, but it requires `ikea_trainset.txt` which was not found in the `indexing_files` folder.

Any other way to visualize the pose data ?

**Comment by sitzikbs** [comment]
in the `indexing_files` directory you have several options for choosing train and test splits. For pose estimation, it probably makes more sense to use `train_cross_subj.txt` which does not have the same person in test and train.
