### ISSUE TITLE
How to extract depth map from depth video?

### ISSUE THREAD

**Issue by Billccx** [IkeaASM/IKEA_ASM_Dataset#18]
Hello!
I need depth map as the input of my pose estimation model, so I downloaded 'ikea_asm_dataset_depth.zip'. I wonder how to change the frame of the depth video to depth map? Is there a factor converting grayscale to depth? 
I am looking forward to your reply. Thanks a lot!

**Comment by sitzikbs** [comment]
See `./toolbox/tb_utils.py`. It has helper functions to get the camera parameters, relative and absolute depth.
