### ISSUE TITLE
Can't download dataset

### ISSUE THREAD

**Issue by DanBmh** [IkeaASM/IKEA_ASM_Dataset#24]
Hi, I can't download the dataset, neither using the links from this repository nor with those from the project's page.

It seems that it is blocked by Google, I get error messages like "Too many users have viewed or downloaded this file recently. " and "Download quota exceeded for this file, so you can't download it at this time"

**Comment by sitzikbs** [comment]
Hi, 
This is a known issue with google drive. Because the files are very large if it blocks if there are multiple attempts to download (I think the goal is to block piracy). 

Some possible solutions: 
1. Try again at a different time / from another station. 
2. Download the raw dataset from the CloudStore link. 
3. if the above don't work you can send me and email and I can try to find a solution. 
Cheers,
Itzik

**Comment by DanBmh** [comment]
Sorry for my late answer, `1.` didn't work as well, but the CloudStore link worked.

**Comment by lulu110997** [comment]
Hi @sitzikbs, 
It seems I am also running into the same issue where google drive is blocking my download attempts from different times/stations. I attempted to download the dataset through CloudStore. However, CloudStor has been decommissioned as of 12pm AEDT on 15 December 2023.

Would you happen to have the dataset uploaded to a different cloud storage service?

**Comment by sitzikbs** [comment]
Hi @lulu110997 , 
Thanks for pointing this out. I will update the README and remove the cloudstore option.

If you send me an email there are several things that we can try. 

We are looking into longer term options at the moment.

**Comment by SergShel** [comment]
I had the same problem, and I found a solution that might be helpful for others.

I was able to access the file in the browser, but when downloading with gdown, I encountered the error "Too many users have viewed or downloaded this file recently." Using gdown with my browser cookies helped me solve the problem.
The solution is described in FAQ in [gdown](https://github.com/wkentaro/gdown)-repo

**Comment by sitzikbs** [comment]
Thanks for the tip! 

You mean following this ?  : 

 If you can access to the file from your browser, downloading cookies file might help.
 Follow this step: 

1. download cookies.txt using browser extensions like ([Get cookies.txt LOCALLY](https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc)); 
2.  mv the cookies.txt to ~/.cache/gdown/cookies.txt;
3. run download again.

If you're using gdown>=5.0.0, it should be able to use the cookies same as your browser."

**Comment by SergShel** [comment]
Yes, that's correct. However, I've discovered that Google restricts frequent downloads of the same file.

When I tried to download the same zip file on a second machine, I received the "Download quota exceeded for this file, so you can't download it at this time" message, even in the browser.

**Comment by sitzikbs** [comment]
Thanks for the feedback. If you are still having trouble please send me an email and I will work out an alternative solution for you to access the files.
