### ISSUE TITLE
Missing extract_features.py in the clip-based I3D code

### ISSUE THREAD

**Issue by divineSix** [IkeaASM/IKEA_ASM_Dataset#28]
The [I3D Readme](https://github.com/IkeaASM/IKEA_ASM_Dataset/blob/master/action/clip_based/i3d/README.md) file has a broken link pointing to an [extract_features.py](https://github.com/IkeaASM/IKEA_ASM_Dataset/blob/master/action/clip_based/i3d/extract_features.py) file that does not exist. Can you please upload the missing script?

**Comment by sitzikbs** [comment]
In the training and testing codes for clipo based i3d there was no use in an `extract_features.py` file. That segment of the readme has now been removed. In `pytorch_i3d.py` there is an `extract_features` method that you can use to extract features.
