### ISSUE TITLE
TypeError: in method 'jet_estimate_normals', argument 1 of type 'Point_set_3_wrapper< CGAL_PS3 >'

### ISSUE THREAD

**Issue by HaziqRazali** [IkeaASM/IKEA_ASM_Dataset#3]
Hello, line 580 with the function `jet_estimate_normals(points, normals, n_neighbors)` in `tb_utils.py` returns the error 

`TypeError: in method 'jet_estimate_normals', argument 1 of type 'Point_set_3_wrapper< CGAL_PS3 >'`

According to the code, `points` is a list of `CGAL.CGAL_Kernel.Point_3`

**Comment by sitzikbs** [comment]
It works fine for me. Please make sure you are using the correct version of CGAL (4.11) and cgal-binding (1.2).

**Comment by HaziqRazali** [comment]
Thank you. Could you tell me how you installed cgal-binding ? The command `conda install -c rustychris python-cgal-bindings` downgrades my python version to 2.7. And what version of python are you using ? Seems like cgal requires python 2 https://pypi.org/project/cgal-bindings/ but opencv etc requires python 3

**Comment by sitzikbs** [comment]
I am using python 3.7 had no issues. I think I  used `pip3 install cgal-bindings`.
