### ISSUE TITLE
Can't download instance segmentation weights

### ISSUE THREAD

**Issue by mona0809** [IkeaASM/IKEA_ASM_Dataset#30]
Thanks for sharing the code and models for this dataset!

Unfortunately, the instance segmentation models can't be downloaded anymore. This link should actually refer to the ResNeXt-101-FPN Mask R-CNN weights: https://drive.google.com/file/d/1QOzGqAWG-cedaQ1hmRL386I93GmJzxTR/view?usp=sharing

**Comment by sitzikbs** [comment]
Does this work for you: 
https://drive.google.com/file/d/1lLNiWU6ILFCgg104FDwWvRMV0iQaGKyp/view?usp=share_link

**Comment by mona0809** [comment]
Yes, thank you very much!
