### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by olga-zats** [IkeaASM/IKEA_ASM_Dataset#35]
Hi!

I have a question concerning frame-wise annotations for action recognition. Which fps did you use for these annotations? Is it 25fps the same as in video?

Thanks!

Best,
Olga

**Comment by sitzikbs** [comment]
Hi Olga,
The sensor provided the raw images at variable FPS and we labeled the raw images. 
The images were postprocessed into video format for compression and sharing. 
I am closing this issue as it does not directly relate to the code. Feel free to send me an email if anything is still unclear.
