### ISSUE TITLE
import i3d_utils?

### ISSUE THREAD

**Issue by ilikeokoge** [IkeaASM/IKEA_ASM_Dataset#6]
Hi, thank you for the great codebase!
I try to execute "action/pose_based/train.py" and encounter the following error:

> No module named 'i3d_utils'

What should I do?

**Comment by sitzikbs** [comment]
Ah yes, I see the issue. the i3d utils file is in the clip_based directory. either add it to path or copy it to the pose_based one for a quick fix. Ill fix this soon.

**Comment by ilikeokoge** [comment]
Thanks for your quick reply! I found that.
