### ISSUE TITLE
quick start of temporal localization for pose based

### ISSUE THREAD

**Issue by ilikeokoge** [IkeaASM/IKEA_ASM_Dataset#8]
I have read your paper.
What I am interested in are the results of Action localization (Appendix).
In your paper, there are only image-based results.
Do you have a pose-based one?
Also, can I try that with this codebase?(Including image-base)

**Comment by sitzikbs** [comment]
We have not tried action localization with poses. You are welcome to try it with this code base. 
Good luck.
