### ISSUE TITLE
Query regarding the Action recognition results 

### ISSUE THREAD

**Issue by vaithak** [IkeaASM/IKEA_ASM_Dataset#9]
You also reported results on your dataset for skeleton-based action recognition models like ST-GCN. My question is regarding the size of the data used for training and evaluating these models. Was only 1% of the data used (for which we have the manual annotations), or an even bigger portion of the dataset was used by using 1% of data with manual annotations along with the other data with pseudo-truth annotations (by using pose estimation models)?

**Comment by sitzikbs** [comment]
for the action recognition, all of the training data was used for training (i.e. with psudo gt).

**Comment by vaithak** [comment]
Thanks for replying :)
Also, does the downloadable dataset on google drive also contains the pseudo-truth annotations for the poses or only the manual annotations (for 1% of the dataset)?

**Comment by vaithak** [comment]
Meaning, does the `annotations` folder in the drive contain the pseudo gt labels?

**Comment by sitzikbs** [comment]
yes.
